apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbit-registry-role
  namespace: rabbit
  labels:
    app: rabbit
rules:
- apiGroups: [""]
  resources: ["endpoints", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbit-registry-rolebinding
  namespace: rabbit
  labels:
    app: rabbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbit-registry-role
subjects:
- kind: ServiceAccount
  name: rabbit-service-account
  namespace: rabbit

