environment: ${MOON_RABBIT_ENVIRONMENT:PROD}
enableClientConfig: ${MOON_RABBIT_ENABLE_CLIENT_CONFIG:false}
enableSwagger: ${MOON_RABBIT_ENABLE_SWAGGER:false}
enableMetrics: ${MOON_RABBIT_ENABLE_METRICS:false}
useDatabase: ${MOON_RABBIT_USE_DATABASE:false}

server:
  name: ${MOON_RABBIT_SERVER_NAME:rabbit}
  namespace: ${MOON_RABBIT_SERVER_NAMESPACE:moon}
  useRandomID: ${MOON_RABBIT_USE_RANDOM_NODE_ID:false}
  metadata:
    tag: ${MOON_RABBIT_METADATA_TAG:rabbit}
    repository: ${MOON_RABBIT_METADATA_REPOSITORY:https://github.com/aide-family/rabbit}
    author: ${MOON_RABBIT_METADATA_AUTHOR:Aide Family}
    email: ${MOON_RABBIT_METADATA_EMAIL:aidecloud@163.com}
  http:
    address: "${MOON_RABBIT_HTTP_ADDRESS:0.0.0.0:8080}"
    network: "${MOON_RABBIT_HTTP_NETWORK:tcp}"
    timeout: "${MOON_RABBIT_HTTP_TIMEOUT:10s}"
  grpc:
    address: "${MOON_RABBIT_GRPC_ADDRESS:0.0.0.0:9090}"
    network: "${MOON_RABBIT_GRPC_NETWORK:tcp}"
    timeout: "${MOON_RABBIT_GRPC_TIMEOUT:10s}"
  job:
    address: "${MOON_RABBIT_JOB_ADDRESS:0.0.0.0:9091}"
    network: "${MOON_RABBIT_JOB_NETWORK:tcp}"
    timeout: "${MOON_RABBIT_JOB_TIMEOUT:10s}"

jwt:
  secret: "${MOON_RABBIT_JWT_SECRET:xxx}"
  expire: "${MOON_RABBIT_JWT_EXPIRE:600s}"
  issuer: "${MOON_RABBIT_JWT_ISSUER:rabbit}"

main:
  username: "${MOON_RABBIT_MAIN_USERNAME:root}"
  password: "${MOON_RABBIT_MAIN_PASSWORD:123456}"
  host: "${MOON_RABBIT_MAIN_HOST:localhost}"
  port: ${MOON_RABBIT_MAIN_PORT:3306}
  database: ${MOON_RABBIT_MAIN_DATABASE:rabbit}
  debug: ${MOON_RABBIT_MAIN_DEBUG:false}
  useSystemLogger: ${MOON_RABBIT_MAIN_USE_SYSTEM_LOGGER:true}
  parameters:
    charset: utf8mb4
    parseTime: "true"
    loc: Asia/Shanghai

jobCore:
  workerTotal: ${MOON_RABBIT_JOB_CORE_WORKER_TOTAL:10}
  timeout: "${MOON_RABBIT_JOB_CORE_TIMEOUT:10s}"
  bufferSize: ${MOON_RABBIT_JOB_CORE_BUFFER_SIZE:1000}
  
registryType: ${MOON_RABBIT_REGISTRY_TYPE:}

cluster:
  name: ${MOON_RABBIT_CLUSTER_NAME:moon.rabbit}
  endpoints: ${MOON_RABBIT_CLUSTER_ENDPOINTS:}
  timeout: ${MOON_RABBIT_CLUSTER_TIMEOUT:10s}

etcd:
  endpoints: ${MOON_RABBIT_ETCD_ENDPOINTS:127.0.0.1:2379}
  username: ${MOON_RABBIT_ETCD_USERNAME:}
  password: ${MOON_RABBIT_ETCD_PASSWORD:}

kubernetes:
  kubeConfig: ${MOON_RABBIT_KUBERNETES_KUBECONFIG:~/.kube/config}

swaggerBasicAuth:
  enabled: ${MOON_RABBIT_SWAGGER_BASIC_AUTH_ENABLED:true}
  username: ${MOON_RABBIT_SWAGGER_BASIC_AUTH_USERNAME:moon.rabbit}
  password: ${MOON_RABBIT_SWAGGER_BASIC_AUTH_PASSWORD:rabbit.swagger}

metricsBasicAuth:
  enabled: ${MOON_RABBIT_METRICS_BASIC_AUTH_ENABLED:true}
  username: ${MOON_RABBIT_METRICS_BASIC_AUTH_USERNAME:moon.rabbit}
  password: ${MOON_RABBIT_METRICS_BASIC_AUTH_PASSWORD:rabbit.metrics}

configPaths: ${MOON_RABBIT_CONFIG_PATHS:}
messageLogPath: ${MOON_RABBIT_MESSAGE_LOG_PATH:}