environment: DEV
server:
  name: moon.rabbit
  useRandomID: true
  metadata:
    tag: rabbit
  # http:
  #   address: 0.0.0.0:8080
  #   network: tcp
  #   timeout: 10s
  # grpc:
  #   address: 0.0.0.0:9090
  #   network: tcp
  #   timeout: 10s

jwt:
  secret: xxx
  expire: 10m
  issuer: rabbit
  allowList:
    - /rabbit.api.v1.Health/HealthCheck
namespaceAllowList:
  - /rabbit.api.v1.Namespace/CreateNamespace
  - /rabbit.api.v1.Namespace/UpdateNamespace
  - /rabbit.api.v1.Namespace/UpdateNamespaceStatus
  - /rabbit.api.v1.Namespace/DeleteNamespace
  - /rabbit.api.v1.Namespace/GetNamespace
  - /rabbit.api.v1.Namespace/ListNamespace

main:
  username: root
  password: '123456'
  host: localhost
  port: 3306
  database: rabbit
  debug: true
  useSystemLogger: false
  parameters:
    charset: utf8mb4
    parseTime: true
    loc: Asia/Shanghai

# biz:
#   <namespace>,<namespace2>:
#     username: root
#     password: '123456'
#     host: localhost
#     port: 3306
#     database: rabbit1
#     parameters:
#       charset: utf8mb4
#       parseTime: true
#       loc: Asia/Shanghai

#   <namespace3>,<namespace4>:
#     username: root
#     password: '123456'
#     host: localhost
#     port: 3306
#     database: rabbit2
#     parameters:
#       charset: utf8mb4
#       parseTime: true
#       loc: Asia/Shanghai

eventBus:
  workerCount: 1
  timeout: 10s

registryType: ETCD

clusters:
  - name: rabbit01
    endpoint: discovery:///moon.rabbit
    protocol: GRPC
    timeout: 10s
  # - name: rabbit02
  #   endpoint: 127.0.0.1:9090
  #   protocol: GRPC
  #   timeout: 10s

etcd:
  endpoints:
    - http://127.0.0.1:2379
  username:
  password:

# kubernetes:
#   kubeConfig: ~/.kube/config
#   namespace: moon