environment: ${MOON_RABBIT_ENVIRONMENT:PROD}
enableClientConfig: true
server:
  name: ${MOON_RABBIT_NAME:moon.rabbit}
  useRandomID: false
  metadata:
    tag: ${MOON_RABBIT_METADATA_TAG:rabbit}
  http:
    address: "${MOON_RABBIT_HTTP_ADDRESS:0.0.0.0:8080}"
    network: "${MOON_RABBIT_HTTP_NETWORK:tcp}"
    timeout: "${MOON_RABBIT_HTTP_TIMEOUT:10s}"
  grpc:
    address: "${MOON_RABBIT_GRPC_ADDRESS:0.0.0.0:9090}"
    network: "${MOON_RABBIT_GRPC_NETWORK:tcp}"
    timeout: "${MOON_RABBIT_GRPC_TIMEOUT:10s}"

jwt:
  secret: "${MOON_RABBIT_JWT_SECRET:xxx}"
  expire: "${MOON_RABBIT_JWT_EXPIRE:600s}"
  issuer: "${MOON_RABBIT_JWT_ISSUER:rabbit}"

main:
  username: "${MOON_RABBIT_MAIN_USERNAME:root}"
  password: "${MOON_RABBIT_MAIN_PASSWORD:123456}"
  host: "${MOON_RABBIT_MAIN_HOST:localhost}"
  port: ${MOON_RABBIT_MAIN_PORT:3306}
  database: ${MOON_RABBIT_MAIN_DATABASE:rabbit}
  debug: false
  useSystemLogger: true
  parameters:
    charset: utf8mb4
    parseTime: "true"
    loc: Asia/Shanghai

eventBus:
  workerCount: ${MOON_RABBIT_EVENT_BUS_WORKER_COUNT:1}
  timeout: ${MOON_RABBIT_EVENT_BUS_TIMEOUT:10s}

registryType: ${MOON_RABBIT_REGISTRY_TYPE:}

cluster:
  name: ${MOON_RABBIT_CLUSTER_NAME:rabbit}
  endpoints: ${MOON_RABBIT_CLUSTER_ENDPOINTS:localhost:9090}
  protocol: ${MOON_RABBIT_CLUSTER_PROTOCOL:GRPC}
  timeout: ${MOON_RABBIT_CLUSTER_TIMEOUT:10s}

etcd:
  endpoints: ${MOON_RABBIT_ETCD_ENDPOINTS:127.0.0.1:2379}
  username: ${MOON_RABBIT_ETCD_USERNAME:}
  password: ${MOON_RABBIT_ETCD_PASSWORD:}

kubernetes:
  kubeConfig: ${MOON_RABBIT_KUBERNETES_KUBECONFIG:~/.kube/config}
  namespace: ${MOON_RABBIT_KUBERNETES_NAMESPACE:moon}